### ISSUE TITLE
Confirm non-existence of export mailbox before hashing mails

### ISSUE THREAD

**Issue by danielneilson** [kdeldycke/mail-deduplicate#119]
mdedup wants to create a new mailbox in the location specified by --export, and if the location exists a `FileExistsError` is raised by `create_box`.

Because this comes after the mail has been hashed, and the hashing is the time-consuming part of the process, one ends up having to re-hash if the mailbox already exists. Although it is a user error, it is annoying to have to re-hash.

So it would be nice if mdedup could check that the export destination doesn't exist, and throw the exception if it does, before the hashing takes place.

**Comment by kdeldycke** [comment]
Ah yes, you're right. Totally makes sense. The current implementation is quite naive indeed. Shouldn't be that hard to fix. I'll put that on my todo list.

**Comment by kdeldycke** [comment]
Just implemented that upstream. Should be part of the next release.

**Comment by kdeldycke** [comment]
`v6.0.1` has just been released with this change.

**Comment by danielneilson** [comment]
Great, thanks for getting to it so quickly! I've been cleaning up more than a decade of emails, really appreciating mdedup

**Comment by kdeldycke** [comment]
A journey which [started 10 years ago](https://github.com/kdeldycke/mail-deduplicate/releases/tag/v0.0.0)! 😄
