### ISSUE TITLE
Link to docs from `README.md` is broken

### ISSUE THREAD

**Issue by rrthomas** [kdeldycke/mail-deduplicate#153]
#### Preliminary checks

* [X] I am running the latest version
* [X] I have [read the Code of Conduct](https://github.com/kdeldycke/mail-deduplicate/blob/develop/.github/code-of-conduct.md)
* [X] I have checked there is not other [Issues](https://github.com/kdeldycke/mail-deduplicate/issues) or [Pull Requests](https://github.com/kdeldycke/mail-deduplicate/pulls) covering the same topic to open

#### Describe the bug

The [link](https://mail-deduplicate.readthedocs.io/) to `readthedocs` from `README.md` is broken.

**Comment by leggewie** [comment]
I can confirm this.  Looks like Kevin is trying to deal with this issue in #66.  The [previous link](https://maildir-deduplicate.readthedocs.io) is still up.

**Comment by kdeldycke** [comment]
Ah yes. That's already covered by #66. I need to dedicate some times for admin work on that front to fix it once for all.

Thanks @rrthomas for the report and @leggewie for bug triaging!
