### ISSUE TITLE
Add Python 3.6 support

### ISSUE THREAD

**Issue by leggewie** [kdeldycke/mail-deduplicate#154]
The way I understand it, mail-deduplicate now requires python 3.7 or later.  Bionic is on 3.6. Given that it is an LTS release of Ubuntu would it be possible to support python 3.6 as well?

**Comment by leggewie** [comment]
Related to this, version 3.0.0 is still available for those on python versions lower than 3.7.  I would think, this might not be intended.

**Comment by kdeldycke** [comment]
While mail-deduplicate version 3.0.0 is working on paper with python versions lower than 3.7, it is so full of issues that I do not recommend using it.

I aggressively deprecated Python 3.6 and required Python 3.7 while I was repackaging the whole project in commit: https://github.com/kdeldycke/mail-deduplicate/commit/4908e33b5e6bebe2a7964cba1e28a15b910cd5dd for the v4.0.0 release.

There might be not a lot of work to do to have Python 3.6 support. I can help you polish a pull request to had 3.6 support. Start by adding 3.6 in the CI test code and package requirements. Did you tried to run the code under Python 3.6 in your environment?

**Comment by leggewie** [comment]
I certainly agree with your push to move on in principle.

All I did locally so far was to lower the requirements for python from ^3.7 to ^3.6 in pyproject.toml, simply to get things running for me on bionic.  Afterwards, I produced the wheel with poetry and installed via pip.  All issues I've run into seem to be unspecific to python 3.6 and were reported in this tracker.

I shall open a new branch at https://github.com/leggewie/mail-deduplicate/commits/bionic

**Comment by kdeldycke** [comment]
Thanks @leggewie for trying that out! Your `bionic` branch looks good to me. Feel free to propose it as a PR. We'll see how the test suite react to that.

**Comment by leggewie** [comment]
Before closing this ticket, should version 3.0.0 remain on pypi.org, possibly for users of python2?

**Comment by kdeldycke** [comment]
The general rule is to not purge any of the the history of released packages on PyPi. If a previous release is bad or botched, just re-release a new revision.

The only case in which it make worth the effort removing old packages is if it got malware or private data in it! ;)

**Comment by leggewie** [comment]
I see.  Makes sense in general.  Users of python 3.6 and below get the very outdated (and I suspect completely unsupported) software that way which isn't ideal, though.

**Comment by kdeldycke** [comment]
> I see. Makes sense in general. Users of python 3.6 and below get the very outdated (and I suspect completely unsupported) software that way which isn't ideal, though.

Yes. Until we release a brand new version that supports 3.6 thanks to your work at #169 ! 😃
