### ISSUE TITLE
`--help` option and naked `mdedup` calls must print the same help screen

### ISSUE THREAD

**Issue by leggewie** [kdeldycke/mail-deduplicate#160]
#### Preliminary checks

* [x] I am running the latest version
* [x] I have [read the Code of Conduct](https://github.com/kdeldycke/mail-deduplicate/blob/develop/.github/code-of-conduct.md)
* [x] I have checked there is not other [Issues](https://github.com/kdeldycke/mail-deduplicate/issues) or [Pull Requests](https://github.com/kdeldycke/mail-deduplicate/pulls) covering the same topic to open

#### Describe the bug

`mdedup --help` says `-s, --strategy [...] Description of each strategy is available at the bottom.`  However, there is no description.

**Comment by kdeldycke** [comment]
Just found out the issue: `mdedup --help` and naked `mdedup` calls doesn't not produces the same output.

The fix would be to wrap/patch the original `--help` option call and plug in there the code producing the enhanced help screen from: https://github.com/kdeldycke/mail-deduplicate/blob/f423b414c400d21e338edf09bf904d39697fc7b8/mail_deduplicate/cli.py#L276-L304

**Comment by kdeldycke** [comment]
The issue with help screens has been fixed by migrating to [`click-extra`](https://github.com/kdeldycke/click-extra). The fix is available in the brand new release of mail-deduplicate 7.0.0.
