### ISSUE TITLE
warn users of the 3.x release of the unsupported status

### ISSUE THREAD

**Issue by leggewie** [kdeldycke/mail-deduplicate#172]
I was going to prepare a pull request but apparently github does not allow a pull request to open a new git branch.  I suggest to branch a python2 branch off the v3.0.0 tag and point it to the tip of the [python2 branch I prepared for the purpose](https://github.com/leggewie/mail-deduplicate/tree/python2).  I then suggest to release a 3.0.1 version to PyPi.

I've taken it as far as I was able to for now, but poetry would not let me compile it.  If you don't like the three-second timer, I added it in a separate commit you can easily revert or drop in a rebase.

The motivation for this branch and proposed release comes from the discussion we had in #154.  I'm not concerned with users of python3.5 and older python3.  For all I know, they must have explicitly chosen that older version of python3.  I'm concerned about python2 users, though.  Not everybody has made the switch away from python2, yet.  Bionic actually still uses python2 by default and I wouldn't be surprised if other stability-minded OS are in the same situation.  

I don't feel at ease that those users are provided with software without an indication of its lack of support and more importantly without indication that there is an easy way for them to get supported software.

**Comment by leggewie** [comment]
I got a little further now and will push a few more commits to my branch.

**Comment by kdeldycke** [comment]
I'm surprised by your extra care about an old and obsolete version but I appreciate the effort nonetheless! 🙂

I guess your proposal is a good way to discover and start playing with the code base so that might indeed be a good starting exercise! 😀

I just created a `v3` branch to the repository, so you can propose your changes against that in a PR.

**Comment by leggewie** [comment]
I'm an LTS kind of guy.  I don't like my machine changing underneath me all the time, requiring my attention to fix the latest stuff.  I also like to polish things up, so this was something I ran across while trying to do meaningful work with mdedup.  "Real devs" might have the bleeding edge of everything, but I am fairly certain the majority of the ordinary users regularly run into preventable grief.

**Comment by leggewie** [comment]
It [works](https://asciinema.org/a/wsu9tzPaxXkYb68eLuNTjwii0)

**Comment by kdeldycke** [comment]
[mail-deduplicate v3.0.1](https://pypi.org/project/mail-deduplicate/3.0.1/) has just been released:
* https://pypi.org/project/mail-deduplicate/3.0.1/
* https://github.com/kdeldycke/mail-deduplicate/compare/v3.0.0...v3.0.1
* https://github.com/kdeldycke/mail-deduplicate/tree/v3.0.1

We can now close this issue.
