### ISSUE TITLE
update project description

### ISSUE THREAD

**Issue by leggewie** [kdeldycke/mail-deduplicate#174]
The about tagline for this repo reads "e-mail CLI to deduplicate mails from maildir folders".  Mail-dedupe supports mailformats other than maildir by now.  Time to update.

**Comment by leggewie** [comment]
Update the link to https://maildir-deduplicate.readthedocs.io/ (404) with the new https://mail-deduplicate.readthedocs.io/ while you are at it (the correct link is at the bottom of the repo page, the wrong one right under "About").

**Comment by kdeldycke** [comment]
> The about tagline for this repo reads "e-mail CLI to deduplicate mails from maildir folders". Mail-dedupe supports mailformats other than maildir by now. Time to update.

Good point! I'll reuse the one from the `pyproject.toml` file then.

**Comment by kdeldycke** [comment]
All done. Thanks @leggewie for your eagle eye!
