### ISSUE TITLE
Add option to ignore single messages when performing any actions

### ISSUE THREAD

**Issue by djwf** [kdeldycke/mail-deduplicate#203]
I'm frustrated when I perform the following operations:
- Select one of each duplicate, as well as the single messages, and move to a mailbox
- Select all of the messages that duplicate the messages selected in the previous step, and move to a different mailbox. 

The solution I'd like to see is described in  #146 (response https://github.com/kdeldycke/mail-deduplicate/issues/146#issuecomment-763799295), and provides the option to ignore the single messages in any actions (only act upon messages that are part of a duplicate set).

**Comment by kdeldycke** [comment]
This has likely been fixed upstream with #286. It will be packaged with `mail-deduplicate` 6.2 that is going to be released soon.
