### ISSUE TITLE
iteritems is python2-only

### ISSUE THREAD

**Issue by leggewie** [kdeldycke/mail-deduplicate#247]
https://github.com/kdeldycke/mail-deduplicate/blob/f423b414c400d21e338edf09bf904d39697fc7b8/mail_deduplicate/deduplicate.py#L361

Am I wrong to think that .iteritems is python2-only?

**Comment by kdeldycke** [comment]
You're right, same method according: https://docs.python.org/3/library/mailbox.html?highlight=iteritems#mailbox.Mailbox.iteritems

Feel free to propose a change! :)

**Comment by leggewie** [comment]
Actually, I'm not so sure anymore.  Above code is not the [built-in dict.items type](https://docs.python.org/3.8/library/stdtypes.html?highlight=items#dict.items) I incorrectly assumed it to be.  The [built-in dict.iteritems](https://docs.python.org/2.7/library/stdtypes.html?highlight=iteritems#dict.iteritems) is indeed python2-only.  But box is a mailbox-object using the iteritems-class from the mailbox module.  So, it's not a case of python2ism (or else we'd see a crash with python3).

Closing as invalid.
