### ISSUE TITLE
-s discard-newer -a delete-discarded isn't deleting any mail

### ISSUE THREAD

**Issue by kirrus** [kdeldycke/mail-deduplicate#270]
#### Preliminary checks

* [X] I am running the latest version
* [X] I have [read the Code of Conduct](https://github.com/kdeldycke/mail-deduplicate/blob/develop/.github/code-of-conduct.md)
* [X] I have checked there is not other [Issues](https://github.com/kdeldycke/mail-deduplicate/issues) or [Pull Requests](https://github.com/kdeldycke/mail-deduplicate/pulls) covering the same topic to open

#### Describe the bug

Trying to delete 'all' older emails that are duplicates, error messages indicating no mails will be deleted are printed.

As a sidenote, this particular scan has been running for a week so far, on 3300 emails, and has yet to complete. I'm worried that the Warnings indicate that it's not going to have selected anything to delete even when it completes. It's using 15.7GB of RAM, of which the majority is in SWAP because this system only has 4GB RAM.

#### To reproduce

1. The full `mdedup` CLI invocation you used.

   ```shell-session
   $ /mdedup --dry-run -i maildir -s discard-newer -a delete-discarded ./my_maildir/
   ```

#### Expected behavior

All 'newer' emails be selected for deletion

#### CLI output

```shell-session
▒ 5 mails sharing hash 47dfeff7be8be6af507bfef326aa1d3ae889577024ca169b87a3f085
Check mail differences are below the thresholds.
Select all mails sharing the oldest 1610466501 timestamp...
warning: Skip set: all 5 mails within were selected. The strategy criterion was not able to discard some.
```

#### Environment

All data on execution context as provided by `$ mdedup --version`:
```shell-session
$ mdedup --version
mdedup 6.1.3
{'username': '-', 'guid': '6e84bceff95dbe900610213cbb0f018', 'hostname': '-', 'hostfqdn': '-', 'uname': {'system': 'Linux', 'node': '-', 'release': '4.19.0-14-amd64', 'version': '#1 SMP Debian 4.19.171-2 (2021-01-30)', 'machine': 'x86_64', 'processor': ''}, 'linux_dist_name': 'debian', 'linux_dist_version': '10.6', 'cpu_count': 2, 'fs_encoding': 'utf-8', 'ulimit_soft': 1024, 'ulimit_hard': 1048576, 'cwd': '-', 'umask': '0o2', 'python': {'argv': '-', 'bin': '-', 'version': '3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]', 'compiler': 'GCC 8.3.0', 'build_date': 'Jan 22 2021 20:04:44', 'version_info': [3, 7, 3, 'final', 0], 'features': {'openssl': 'OpenSSL 1.1.1d  10 Sep 2019', 'expat': 'expat_2.2.6', 'sqlite': '3.27.2', 'tkinter': '', 'zlib': '1.2.11', 'unicode_wide': True, 'readline': True, '64bit': True, 'ipv6': True, 'threading': True, 'urandom': True}}, 'time_utc': '2021-07-16 13:33:48.242631', 'time_utc_offset': 0.0, '_eco_version': '1.0.1'}
```

#### Additional context

Really struggled to understand the docs to do what I needed here!

**Comment by kdeldycke** [comment]
All `*-discarded` were not implemented. This has been fixed by #290 and was just merged upstream. The next release of `mail-deduplicate` will make @kirrus CLI work for good.
