### ISSUE TITLE
`boltons.ecoutils.pprint` error on Python 3.10

### ISSUE THREAD

**Issue by ian-kelling** [kdeldycke/mail-deduplicate#361]
```pytb
Traceback (most recent call last):
  File "/home/iank/.local/bin/mdedup", line 5, in <module>
    from mail_deduplicate.cli import mdedup
  File "/home/iank/.local/lib/python3.10/site-packages/mail_deduplicate/__init__.py", line 25, in <module>
    from boltons.ecoutils import get_profile
  File "/home/iank/.local/lib/python3.10/site-packages/boltons/ecoutils.py", line 357, in <module>
    _real_safe_repr = pprint._safe_repr
AttributeError: module 'pprint' has no attribute '_safe_repr'. Did you mean: 'saferepr'?
```

looks like it is related to newer python 3.10 than this was developed on

**Comment by kdeldycke** [comment]
Ah yes. Thanks to the report. I fixed this upstream in [`click-extra`](https://github.com/kdeldycke/click-extra). I need to integrate the later to `mail-deduplicate` to modernize it a bit, but for the moment I'm focused on finishing what I started on [`meta-package-manager`](https://github.com/kdeldycke/meta-package-manager).

Alternative solutions:
- Downgrade to Python < 3.10
- Have @mahmoud release the development version of [`boltons`](https://github.com/mahmoud/boltons), which has a fix for this: https://github.com/mahmoud/boltons/issues/294

**Comment by danielhatton** [comment]
I think the Python upgrade that leads to this issue happens as part of the dist-upgrade from Ubuntu 20.04 to 22.04, so it'll be becoming very common right about now.

**Comment by kdeldycke** [comment]
The issue has been fixed with a migration to [click-extra](https://github.com/kdeldycke/click-extra). The fix is available in the brand new release of mail-deduplicate 7.0.0.

**Comment by kdeldycke** [comment]
Thanks @danielhatton for taking the time to check for the fix! 👍

**Comment by ian-kelling** [comment]
Also just want to say thank you!
