### ISSUE TITLE
No docs

### ISSUE THREAD

**Issue by dahamsta** [kdeldycke/mail-deduplicate#368]
No docs at https://mail-deduplicate.readthedocs.io/ , getting a 404.

**Comment by dahamsta** [comment]
Thanks. Is there a copy somewhere else? I see there's docs in the repo, but they don't render as-is, and I'm not sure how to get them to. :)

**Comment by kdeldycke** [comment]
I just refactored the documentation system 13 hours ago. Some stuff needs to be fixed and polished, but it is now available at: https://kdeldycke.github.io/mail-deduplicate/
