### ISSUE TITLE
mdedup appears to stop for no reason

### ISSUE THREAD

**Issue by mkaito** [kdeldycke/mail-deduplicate#49]
I have a rather large Maildir folder with a total of 11966 files. Almost every mail is duplicated, courtesy of a misconfigured mail sync tool. When running mdedup on it, it seems to just stop with exit code 1 and no interesting log output. It reaches 4% before stopping, but setting the `-i` flag has it stop at 2%, oddly enough.

Here's a paste of said log in debug mode: http://dpaste.com/3X57Z0V

**Comment by mkaito** [comment]
Appears to be a pythong 2 issue. Running with python 3 results in an encoding error, which is unrelated. However, running with `-i` in python 3 still shows the same behaviour as above, terminating with no fanfare at 4%.

**Comment by mkaito** [comment]
Actually, seems to be an encoding error in py2  as well. The stuff one gets sent in mails can't be relied upon to be squeaky clean, so perhaps we should try to recover from this error somehow?

**Comment by kdeldycke** [comment]
Thanks for the update. The idea would be first to detect and skip badly encoded mails, in the spirit of #47.

After that we can go further and try working on improving the parsing of badly encoded emails as discussed in #46.

**Comment by kdeldycke** [comment]
This bug has likely been fixed in all the old PR that have been merged upstream since them. Let's close it.
