### ISSUE TITLE
Confusing size/content flag description

### ISSUE THREAD

**Issue by jlovison** [kdeldycke/mail-deduplicate#51]
Looking at the source, setting `-1` to either the size or content flags completely ignores potential changes in the size or content.

The help text implies that setting to `-1` is equivalent to setting to zero (i.e. no difference in size/content allowed), whereas it's actually the opposite (any difference in size/content allowed).

**Comment by kdeldycke** [comment]
Sorry, took me 3 years but the description has finally been fixed! 😄
