### ISSUE TITLE
Numerous problems with click_log

### ISSUE THREAD

**Issue by ghost** [kdeldycke/mail-deduplicate#65]
click_log no longer has init() or get_level(), so maildir-deduplicate doesn't work.  Any chance of replacing click_log with something that has a more stable API?

**Comment by rixx** [comment]
The issues seem to be fixed in ``master``, which is not released yet. If we could get @kdeldycke to issue a release, that would be the best, I think. Until then, you can install the current master via ``pip install git+https://github.com/kdeldycke/maildir-deduplicate``.

**Comment by kdeldycke** [comment]
This issue has been solved with the update to latest `click-log` package. See: https://github.com/kdeldycke/mail-deduplicate/commit/3c30b0fb49f0fe9d962d31b1b463ad93216c1b69

**Comment by kdeldycke** [comment]
FYI, this duplicates #63.
