### ISSUE TITLE
Packaging for openSUSE: Tests fail due to missing fixture "invoke"?

### ISSUE THREAD

**Issue by johanneskastl** [kdeldycke/mail-deduplicate#787]
Dear Kevin,

I am trying to package mail-deduplicate for openSUSE. I downgraded click-extra for now to work around #784 for now.

Now the tests fail with a missing fixture, e.g.:

```
[   21s] __________ ERROR at setup of test_nonexistent_path[./dummy_maildir/] ___________
[   21s] file /home/abuild/rpmbuild/BUILD/mail_deduplicate-7.5.0/tests/test_mail_box.py, line 21
[   21s]   @pytest.mark.parametrize("source", ["./dummy_maildir/", "./__init__.py"])
[   21s]   def test_nonexistent_path(invoke, source):
[   21s] E       fixture 'invoke' not found
[   21s] >       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
[   21s] >       use 'pytest --fixtures [testpath]' for help on them.
[   21s] 
[   21s] /home/abuild/rpmbuild/BUILD/mail_deduplicate-7.5.0/tests/test_mail_box.py:21
```

pytest version is `8.3.3`.
The package is built for four different python versions currently, 3.10 to 3.13.

Do you have an idea,where this missing fixture can be found?

Kind Regards,
Johannes

**Comment by kdeldycke** [comment]
Click extra moved a lot since the last release of Mail Deduplicate. I just fixed this issue upstream. Expect a brand new `mail-deduplicate` v7.6.0 release in a couple of hours.
