### ISSUE TITLE
TypeError: apply_strategy() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by leggewie** [kdeldycke/mail-deduplicate#88]
I'm using version 3.0.0 of mdedupe.  Thank you so much for providing this tool.

My python foo is not that strong, but I believe I've come across a genuine bug and have a rough idea where it is coming from.  The [apply_strategy](https://github.com/kdeldycke/mail-deduplicate/blob/395291b24415c3c5891e34288eda034ab6e228f0/mail_deduplicate/deduplicate.py#L173) function in the [DuplicateSet](https://github.com/kdeldycke/mail-deduplicate/blob/395291b24415c3c5891e34288eda034ab6e228f0/mail_deduplicate/deduplicate.py#L50) class accepts no positional argument other than self.  Yet, it is being [called with self.conf.strategy as a parameter](https://github.com/kdeldycke/mail-deduplicate/blob/395291b24415c3c5891e34288eda034ab6e228f0/mail_deduplicate/deduplicate.py#L593).  Kindly, please have a look.

```
$ mdedup deduplicate -n -s delete-matching-path -rDAMAGED2020 ~/Maildir/.DAMAGED20200924.Trash/ ~/Maildir/.Trash/
[...]...
=== Phase #2: deduplicate mails.
The delete-matching-path strategy will be applied on each duplicate set.
--- 2 mails sharing hash bb2bc9037f04dbdc50519fc7ce88e7694fcb2ececbf49a3fb9d37f5b
Check that mail differences are within the limits.
Traceback (most recent call last):
[...]
  File "/home/leggewie/.local/lib/python3.6/site-packages/mail_deduplicate/deduplicate.py", line 593, in run
    duplicates.apply_strategy(self.conf.strategy)
TypeError: apply_strategy() takes 1 positional argument but 2 were given
```

[discussion on stackoverflow](https://stackoverflow.com/questions/23944657/typeerror-method-takes-1-positional-argument-but-2-were-given)

**Comment by kdeldycke** [comment]
This has been fixed uopsteam in https://github.com/kdeldycke/mail-deduplicate/commit/b0f00e40f2e387141f535d26d54844a467ea5324 and will be part of the upcoming v4.0.0 release.
