### ISSUE TITLE
No deletion: all mail differences within limits

### ISSUE THREAD

**Issue by vikasrawal** [kdeldycke/mail-deduplicate#97]
I am using 

`mdedup -C -1 -S -1 -s delete-smaller maildirname`

But I still get "Check that mail differences are within the limits." messages, and nothing is deleted. All duplicates are either ignored or skipped.
 
```
│ Mails      │   Metric │
╞════════════╪══════════╡
│ Found      │      227 │
├────────────┼──────────┤
│ Rejected   │        0 │
├────────────┼──────────┤
│ Kept       │      227 │
├────────────┼──────────┤
│ Unique     │        7 │
├────────────┼──────────┤
│ Duplicates │      220 │
├────────────┼──────────┤
│ Deleted    │        0 │
╘════════════╧══════════╛
╒══════════════════════════════════════╤══════════╕
│ Duplicate sets                       │   Metric │
╞══════════════════════════════════════╪══════════╡
│ Total                                │      117 │
├──────────────────────────────────────┼──────────┤
│ Ignored                              │        7 │
├──────────────────────────────────────┼──────────┤
│ Skipped                              │      110 │
├──────────────────────────────────────┼──────────┤
│ Rejected (bad encoding)              │        0 │
├──────────────────────────────────────┼──────────┤
│ Rejected (too dissimilar in size)    │        0 │
├──────────────────────────────────────┼──────────┤
│ Rejected (too dissimilar in content) │        0 │
├──────────────────────────────────────┼──────────┤
│ Deduplicated                         │        0 │
```

What might be wrong?

Is there a way to rename the files rather than delete duplicates?

Thanks for help.

Vikas

**Comment by kdeldycke** [comment]
I just released v4.0.0 of the CLI: https://github.com/kdeldycke/mail-deduplicate/releases/tag/v4.0.0

Can you try that out please? And tell me if it fixes your issue?

**Comment by kdeldycke** [comment]
As for you suggestion of renaming the file instead of deleting the duplicates, I created a feature request for this at: https://github.com/kdeldycke/mail-deduplicate/issues/98

**Comment by vikasrawal** [comment]
The above result is for V4.0.0.

Thanks for responding.

Best wishes.

**Comment by kdeldycke** [comment]
Can you run the CLI in debug mode (`--verbosity=DEBUG` parameter) and identify the relevant logs? Better yet, can you provide the content of two mails, the corresponding logs and your expected results?

**Comment by vikasrawal** [comment]
Here is the full log:

debug: Verbosity set to DEBUG.
=== Phase #1: load mails.
Opening /home/user/mailstore/maildebug as a maildir...
8 mails found.
=== Phase #2: compute mail hashes.
debug: Fetching '1547203541.11011_504.cheherkalan,U=20' from /home/user/mailstore/maildebug ...
debug: Hash is 9d2485741354281f58ba92688e05f088c83e551ff6ec6cc2252f06cc for /home/user/mailstore/maildebug:1547203541.11011_504.cheherkalan,U=20.
debug: Fetching '1554192756.30952_11.katkuian,U=4' from /home/user/mailstore/maildebug ...
debug: Hash is 3bcaf26acb27f8208d7154bc21af9ed571972c6a7e62f86be770efc6 for /home/user/mailstore/maildebug:1554192756.30952_11.katkuian,U=4.
debug: Fetching '1553857221.5272_4.katkuian,U=3' from /home/user/mailstore/maildebug ...
debug: Hash is 1e8171a2c8233027ea605050e0ec6436f0407126e81cf78846e272ec for /home/user/mailstore/maildebug:1553857221.5272_4.katkuian,U=3.
debug: Fetching '1538554457.5520_1.khandrai,U=18' from /home/user/mailstore/maildebug ...
debug: Hash is 80971bb2208dea406972cdf9e5355fedbbcf79d02cae1c1b2b58262d for /home/user/mailstore/maildebug:1538554457.5520_1.khandrai,U=18.
debug: Fetching '1547203541.11011_505.cheherkalan,U=21' from /home/user/mailstore/maildebug ...
debug: Hash is d84285c90793a1587a865d28e2a46e800a04d12372b870c74430beea for /home/user/mailstore/maildebug:1547203541.11011_505.cheherkalan,U=21.
debug: Fetching '1553754009.23991_4.katkuian,U=2' from /home/user/mailstore/maildebug ...
debug: Hash is 254f70b2110a1d567028f3195f0c6d5c1bdf72f5a8a955f4ab15f917 for /home/user/mailstore/maildebug:1553754009.23991_4.katkuian,U=2.
debug: Fetching '1538554457.5520_2.khandrai,U=19' from /home/user/mailstore/maildebug ...
debug: Hash is ef8029119e1f2cbb3f8145acff16f02a80a6abef908e4300b70cd021 for /home/user/mailstore/maildebug:1538554457.5520_2.khandrai,U=19.
debug: Fetching '1553754006.23991_3.katkuian,U=1' from /home/user/mailstore/maildebug ...
debug: Hash is 50c95be48ad6c81af0163b6f156e72497a17683c037ccb6c0c770e9d for /home/user/mailstore/maildebug:1553754006.23991_3.katkuian,U=1.
=== Phase #3: deduplicate mails.
delete-smaller strategy will be applied on each duplicate set.
debug: --- 1 mails sharing hash 9d2485741354281f58ba92688e05f088c83e551ff6ec6cc2252f06cc
debug: <DuplicateSet hash=9d2485741354281f58ba92688e05f088c83e551ff6ec6cc2252f06cc, size=1, conf=<mail_deduplicate.Config object at 0x7f91731c20d0>, pool=frozenset({<mail_deduplicate.mail.Mail object at 0x7f91732e66d0>})> created.
debug: Ignore set: only one message found.
debug: --- 1 mails sharing hash 3bcaf26acb27f8208d7154bc21af9ed571972c6a7e62f86be770efc6
debug: <DuplicateSet hash=3bcaf26acb27f8208d7154bc21af9ed571972c6a7e62f86be770efc6, size=1, conf=<mail_deduplicate.Config object at 0x7f91731c20d0>, pool=frozenset({<mail_deduplicate.mail.Mail object at 0x7f9172dc0040>})> created.
debug: Ignore set: only one message found.
debug: --- 1 mails sharing hash 1e8171a2c8233027ea605050e0ec6436f0407126e81cf78846e272ec
debug: <DuplicateSet hash=1e8171a2c8233027ea605050e0ec6436f0407126e81cf78846e272ec, size=1, conf=<mail_deduplicate.Config object at 0x7f91731c20d0>, pool=frozenset({<mail_deduplicate.mail.Mail object at 0x7f9172dc0460>})> created.
debug: Ignore set: only one message found.
debug: --- 1 mails sharing hash 80971bb2208dea406972cdf9e5355fedbbcf79d02cae1c1b2b58262d
debug: <DuplicateSet hash=80971bb2208dea406972cdf9e5355fedbbcf79d02cae1c1b2b58262d, size=1, conf=<mail_deduplicate.Config object at 0x7f91731c20d0>, pool=frozenset({<mail_deduplicate.mail.Mail object at 0x7f9172dc0400>})> created.
debug: Ignore set: only one message found.
debug: --- 1 mails sharing hash d84285c90793a1587a865d28e2a46e800a04d12372b870c74430beea
debug: <DuplicateSet hash=d84285c90793a1587a865d28e2a46e800a04d12372b870c74430beea, size=1, conf=<mail_deduplicate.Config object at 0x7f91731c20d0>, pool=frozenset({<mail_deduplicate.mail.Mail object at 0x7f9172dc0370>})> created.
debug: Ignore set: only one message found.
debug: --- 1 mails sharing hash 254f70b2110a1d567028f3195f0c6d5c1bdf72f5a8a955f4ab15f917
debug: <DuplicateSet hash=254f70b2110a1d567028f3195f0c6d5c1bdf72f5a8a955f4ab15f917, size=1, conf=<mail_deduplicate.Config object at 0x7f91731c20d0>, pool=frozenset({<mail_deduplicate.mail.Mail object at 0x7f9172dc0910>})> created.
debug: Ignore set: only one message found.
debug: --- 1 mails sharing hash ef8029119e1f2cbb3f8145acff16f02a80a6abef908e4300b70cd021
debug: <DuplicateSet hash=ef8029119e1f2cbb3f8145acff16f02a80a6abef908e4300b70cd021, size=1, conf=<mail_deduplicate.Config object at 0x7f91731c20d0>, pool=frozenset({<mail_deduplicate.mail.Mail object at 0x7f9172dc09d0>})> created.
debug: Ignore set: only one message found.
debug: --- 1 mails sharing hash 50c95be48ad6c81af0163b6f156e72497a17683c037ccb6c0c770e9d
debug: <DuplicateSet hash=50c95be48ad6c81af0163b6f156e72497a17683c037ccb6c0c770e9d, size=1, conf=<mail_deduplicate.Config object at 0x7f91731c20d0>, pool=frozenset({<mail_deduplicate.mail.Mail object at 0x7f9172dc0a00>})> created.
debug: Ignore set: only one message found.
╒════════════╤══════════╕
│ Mails      │   Metric │
╞════════════╪══════════╡
│ Found      │        8 │
├────────────┼──────────┤
│ Rejected   │        0 │
├────────────┼──────────┤
│ Kept       │        8 │
├────────────┼──────────┤
│ Unique     │        8 │
├────────────┼──────────┤
│ Duplicates │        0 │
├────────────┼──────────┤
│ Deleted    │        0 │
╘════════════╧══════════╛
╒══════════════════════════════════════╤══════════╕
│ Duplicate sets                       │   Metric │
╞══════════════════════════════════════╪══════════╡
│ Total                                │        8 │
├──────────────────────────────────────┼──────────┤
│ Ignored                              │        8 │
├──────────────────────────────────────┼──────────┤
│ Skipped                              │        0 │
├──────────────────────────────────────┼──────────┤
│ Rejected (bad encoding)              │        0 │
├──────────────────────────────────────┼──────────┤
│ Rejected (too dissimilar in size)    │        0 │
├──────────────────────────────────────┼──────────┤
│ Rejected (too dissimilar in content) │        0 │
├──────────────────────────────────────┼──────────┤
│ Deduplicated                         │        0 │
╘══════════════════════════════════════╧══════════╛

**Comment by vikasrawal** [comment]
Gives this kind of messages:

--- 2 mails sharing hash c47ac7d8a9c3f103ca756dfb8b789527c0119d67b10b71d0a951c405
debug: <DuplicateSet hash=c47ac7d8a9c3f103ca756dfb8b789527c0119d67b10b71d0a951c405, size=2, conf=<mail_deduplicate.Config object at 0x7f5fab8c40d0>, pool=frozenset({<mail_deduplicate.mail.Mail object at 0x7f5faa3df0a0>, <mail_deduplicate.mail.Mail object at 0x7f5faa3b8070>})> created.
Check that mail differences are within the limits.
Skip checking for size differences.
Skip checking for content differences.
debug: Call delete_smaller() strategy.
Deleting all mails strictly smaller than 627 bytes...
0 candidates found for deletion.
Skip set: no deletion happened.
debug: <DuplicateSet hash=d44f163c514f6a454c4cf080fe8609040dd10ba3728376487d614538, size=2, conf=<mail_deduplicate.Config object at 0x7f5fab8c40d0>, pool=frozenset({<mail_deduplicate.mail.Mail object at 0x7f5faa3f5700>, <mail_deduplicate.mail.Mail object at 0x7f5faa3d8460>})> created.
Check that mail differences are within the limits.
Skip checking for size differences.
Skip checking for content differences.
debug: Call delete_smaller() strategy.
Deleting all mails strictly smaller than 2239 bytes...
0 candidates found for deletion.
Skip set: no deletion happened.
--- 2 mails sharing hash 54480fd2aa7cc864a2c427c7ede98b917426fc418d593918535609d5
debug: <DuplicateSet hash=54480fd2aa7cc864a2c427c7ede98b917426fc418d593918535609d5, size=2, conf=<mail_deduplicate.Config object at 0x7f5fab8c40d0>, pool=frozenset({<mail_deduplicate.mail.Mail object at 0x7f5faa3a4520>, <mail_deduplicate.mail.Mail object at 0x7f5faa3f5460>})> created.
Check that mail differences are within the limits.
Skip checking for size differences.
Skip checking for content differences.
debug: Call delete_smaller() strategy.
Deleting all mails strictly smaller than 85994 bytes...
0 candidates found for deletion.
Skip set: no deletion happened.

**Comment by kdeldycke** [comment]
I just released a new v5.0.0 version: https://github.com/kdeldycke/mail-deduplicate/releases/tag/v5.0.0

Can you check it out please?

**Comment by vikasrawal** [comment]
Nothing seems to be deleted. I have tried different deletion strategies. See the log:

## When using delete-older (date-header)

--- 2 mails sharing hash 01327175d87a9078a30b00ea63574694907b613f2efd06e79f2da5ea
debug: <DuplicateSet hash=01327175d87a9078a30b00ea63574694907b613f2efd06e79f2da5ea, size=2, conf=<mail_deduplicate.Config object at 0x7f78ac2c67c0>, pool=frozenset({<Mail '1553568282.27026_36.katkuian,U=36'>, <Mail '1529304528.22219_280.khandrai,U=36'>})> created.
Check that mail differences are within the limits.
Skip checking for size differences.
Skip checking for content differences.
debug: Call delete_older() strategy.
Select all mails strictly older than the 1453342388 timestamp...
0 candidates found for deletion.



## When using delete-smaller

--- 2 mails sharing hash 01327175d87a9078a30b00ea63574694907b613f2efd06e79f2da5ea
debug: <DuplicateSet hash=01327175d87a9078a30b00ea63574694907b613f2efd06e79f2da5ea, size=2, conf=<mail_deduplicate.Config object at 0x7f03f6c8a7c0>, pool=frozenset({<Mail '1553568282.27026_36.katkuian,U=36'>, <Mail '1529304528.22219_280.khandrai,U=36'>})> created.
Check that mail differences are within the limits.
Skip checking for size differences.
Skip checking for content differences.
debug: Call delete_smaller() strategy.
Select all mails strictly smaller than 0 bytes...
0 candidates found for deletion.

**Comment by kdeldycke** [comment]
I think I have an idea. It seems the sets of two mails are perfectly identical even after all the normalisation and canonicalisation. Which means whatever the strategy selected, there is not enough difference (by date or by size) to choose among the duplicates which one to keep/discard.

All in all, I guess we need a kind of `delete-random` strategy to only keep one mail in the `DuplicateSet`.

**Comment by vikasrawal** [comment]
If it is easier, one could also do keep-alphabetically-first or keep-alphabetically-last using file names. That would also solve the problem.

**Comment by kdeldycke** [comment]
I just implemented `--strategy=select-one`/`--strategy=discard-all-but-one` at https://github.com/kdeldycke/mail-deduplicate/blob/310498263cb06e65543372d9c6cb6fda1618afed/mail_deduplicate/strategy.py#L168-L175 .

This will be part of the upcoming v6.0.0 release, but you can try it out by clone the `develop` branch.

**Comment by kdeldycke** [comment]
Also in v6.0.0. I implemented https://github.com/kdeldycke/mail-deduplicate/issues/98 , i.e. a way to move or copy selected duplicate mails to a brand new box instead of deleting them in place. With all that you should be able to perform the deduplication you're looking for.

**Comment by matclab** [comment]
Just tried with `poetry run mdedup -a delete-selected -s select-all-but-one folder` and it seems to work like a charm.

Thank you.

**Comment by vikasrawal** [comment]
Yes. This is neat.

Vikas

**Comment by kdeldycke** [comment]
Thanks a lot for your feedback! I'll now close this issue as resolved then. I'll probably release v6.0.0 in the next few days.
